schedule updates
ICESAT-2HackWeek/ICESat-2-Hackweek-2023 pull request #32
Opened 2023-07-18 21:40 UTC by aaarendt

some updates coming out of our last team meeting

2023-07-18 22:03 UTC, jomey requested changes

2023-07-18 22:03 UTC, jomey commented on book/schedule.yaml
> +    - Zach Fair
This should be 'Zachary Fair' so the splash page links his name with his profile (automatically)

2023-07-19 14:33 UTC, scottyhq approved these changes

2023-07-19 14:54 UTC, jomey approved these changes

2023-07-19 14:54 UTC, merged