Sea ice tutorial
ICESAT-2HackWeek/ICESat-2-Hackweek-2023 pull request #50
Opened 2023-07-31 00:32 UTC by YoungHyunKoo

Update on sea ice tutorial (07/30/2023)

2023-07-31 17:37 UTC, scottyhq commented
Thank you @YoungHyunKoo ! The notebooks and figures are looking really great. You'll see in the failed checks: 

`StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.`

Notebooks that require interactive user inputs can't be executed top-to-bottom. So I recommend for this case commiting the notebook with *rendered* outputs and skip executing them by adding their paths here:

https://github.com/ICESAT-2HackWeek/ICESat-2-Hackweek-2023/blob/943033ba69ed090405ad4f214b188e1539cf396d/book/_config.yml#L39-L40

2023-07-31 18:46 UTC, scottyhq commented on book/_toc.yml
> +        - file: tutorials/sea_ice/2_ATL10_Sentinel-2
```suggestion
        - file: tutorials/sea_ice/1_sea_ice_tutorial
          sections:
            - file: tutorials/sea_ice/2_ATL10_Sentinel-2
```

2023-07-31 18:48 UTC, scottyhq commented on book/_config.yml
> +    - "**/1_sea_ice_tutorials.ipynb"
```suggestion
    - "**/1_sea_ice_tutorial.ipynb"
```
(extra "s")

2023-07-31 18:51 UTC, scottyhq commented
Please add your data files (*.tif, *.h5) to CryoCloud JupyterHub's shared folder: `/home/jovyan/shared-public`

2023-07-31 19:08 UTC, YoungHyunKoo commented
@scottyhq Hi, Scott. Thank you so much for your help. I just added the files to the `/home/jovyan/shared-public/sea_ice` folder.

2023-08-01 00:40 UTC, scottyhq commented on book/tutorials/sea_ice/2_ATL10_Sentinel-2.ipynb
You can remove a couple pip imports since they are now in the default CryoCloud environment:
```
!pip install earthengine-api
!pip install geemap
```

2023-08-01 00:42 UTC, scottyhq commented on book/tutorials/sea_ice/2_ATL10_Sentinel-2.ipynb
Please remove S2_*.tif files in this pull request. Since you download them in the notebook people will have them locally. Or you can change this line: 

```python
img_name = "/home/jovyan/shared-public/S2_20190916T191509_20190916T191506_T03CVT.tif"
```

2023-08-01 00:44 UTC, scottyhq commented on book/tutorials/sea_ice/2_ATL10_Sentinel-2.ipynb
same with processed_*hdf:

```python
tutorial_data = "/home/jovyan/shared-public"
filename = f"{tutorial_data}/processed_ATL10-02_20190916205836_12340401_005_02.h5"
```

2023-08-01 00:48 UTC, scottyhq requested changes
The failing check is `WARNING: Non-consecutive header level increase; 2 to 4 [myst.header]`. JupyterBook is very picky about section headings in order to automatically create website sidebars. 

You can change `#### Credited by Younghyun Koo` to use bold instead of a heading: `**Credited by Younghyun Koo**`

2023-08-01 13:29 UTC, YoungHyunKoo commented
@scottyhq Thank you so much for your help. I just updated my pull request. I hope it will be fine now.

2023-08-01 18:57 UTC, scottyhq approved these changes
Looks great @YoungHyunKoo . Two optional things if you'd like: 

You can add captions to your excellent figures (e.g. to reference their source)
https://jupyterbook.org/en/stable/content/references.html#reference-figures

If you want you can even add citation entries to the bibliography page (https://github.com/ICESAT-2HackWeek/ICESat-2-Hackweek-2023/blob/main/book/references.bib) and cite them: 

https://jupyterbook.org/en/stable/content/citations.html#citations-and-bibliographies

Just add a comment if you're making any other changes. Otherwise I think we can merge this!

2023-08-02 21:17 UTC, YoungHyunKoo commented
@scottyhq Thank you so much for your comments! I added some captions to the figures and some references.

2023-08-02 21:17 UTC, merged