Add files via upload
ICESAT-2HackWeek/ICESat-2-Hackweek-2023 pull request #72
Opened 2023-08-05 00:50 UTC by michaleaking

uploading readme and GrIMP jupyter notebook for Thursday tutorial

2023-08-07 17:46 UTC, jomey commented
The QA/QC detected some spelling errors:
```
Error: ./book/tutorials/GrIMP/GrIMPtutorial.ipynb:24: formmatted ==> formatted
Error: ./book/tutorials/GrIMP/GrIMPtutorial.ipynb:81: funcitons ==> functions
Error: ./book/tutorials/GrIMP/GrIMPtutorial.ipynb:226: compenent ==> component, competent
Error: ./book/tutorials/GrIMP/GrIMPtutorial.ipynb:226: compenents ==> components, competence
Error: ./book/tutorials/GrIMP/GrIMPtutorial.ipynb:251: accomodate ==> accommodate
Error: ./book/tutorials/GrIMP/GrIMPtutorial.ipynb:419: sucessful ==> successful
Error: ./book/tutorials/GrIMP/GrIMPtutorial.ipynb:628: dictinary ==> dictionary
Error: ./book/tutorials/GrIMP/README.md:67: automically ==> automatically
```

2023-08-08 02:53 UTC, michaleaking reviewed
Reviewed corrections to spelling mistakes in notebook

2023-08-08 16:10 UTC, scottyhq commented on book/tutorials/GrIMP/GrIMPtutorial.ipynb
@michaleaking have you run this notebook on CryoCloud? The following cell gives me a ValueError: 

```python
myVelSeries = nisar.nisarVelSeries() 
myVelSeries.readSeriesFromTiff(myUrls.getCogs(replace='vv', removeTiff=True), url=True, readSpeed=False, useErrors=True, useDT=True)  
myVelSeries.xr
```

```pytb
File /srv/conda/envs/notebook/lib/python3.10/_strptime.py:349, in _strptime(data_string, format)
    347 found = format_regex.match(data_string)
    348 if not found:
--> 349     raise ValueError("time data %r does not match format %r" %
    350                      (data_string, format))
    351 if len(data_string) != found.end():
    352     raise ValueError("unconverted data remains: %s" %
    353                       data_string[found.end():])

ValueError: time data 'image' does not match format '%d%b%y'
```

2023-08-08 16:13 UTC, scottyhq commented on book/tutorials/GrIMP/GrIMPtutorial.ipynb
You'll notice images are not rendered here https://deploy-preview-72--icesat-2-2023.netlify.app/tutorials/grimp/grimptutorial . That is because the website needs to have images in this repository to render on the website. So I recommend an 'images' subfolder. For example: 

`![GrIMP header](/home/jovyan/shared-public/ICESat-2-Hackweek/GrIMP/GrIMP_tutorial_res/GrIMP_header.png)` ->  `![GrIMP header](./images/GrIMP_header.png)`

2023-08-08 16:17 UTC, scottyhq commented on book/tutorials/GrIMP/GrIMPtutorial.ipynb
Also seems a path is either incorrect or file is missing:

```pytb
RasterioIOError: /home/jovyan/GrIMP_tutorial_res/Geotiffs/GL_S1bks_mosaic_uncalibrated._2021-08-05.tif: No such file or directory
```

2023-08-08 16:19 UTC, scottyhq requested changes
Thanks @michaleaking see requested edit above, just want to make sure people can run everything on CryoCloud JupyterHub for Thursday. If something is erroring, we'll either need to remove that code cell / example or fix it

2023-08-08 16:25 UTC, michaleaking commented
@scottyhq Thanks! Things were running on CryoCloud - I will take a look again this morning and address your other comments as well. Be in touch soon!

2023-08-08 23:23 UTC, closed without merging