Hydrology
ICESAT-2HackWeek/ICESat-2-Hackweek-2023 pull request #74
Opened 2023-08-05 01:09 UTC by tplshams

2023-08-07 17:16 UTC, scottyhq commented on book/tutorials/Hydrology/Hackweek.ipynb
I recommend changing `/home/jovyan/shared/ICESat-2-Hackweek/Hydrology` -> `/tmp/Hydrology' (not everyone has write access to `shared`

2023-08-07 17:19 UTC, scottyhq requested changes
Note: failing checks
https://github.com/ICESAT-2HackWeek/ICESat-2-Hackweek-2023/actions/runs/5767906781/job/15638272448?pr=74

`Ensure Clean Notebook` is a reminder to commit a notebook *without* outputs. So `Restart Kernel and Clear all Outputs` from the file menu

2023-08-07 17:50 UTC, jomey commented
Here some spelling errors identified by the QA/QC automation:
```
Error: ./book/tutorials/Hydrology/Hackweek.ipynb:28: respresented ==> represented
Error: ./book/tutorials/Hydrology/Hackweek.ipynb:53: demostration ==> demonstration
Error: ./book/tutorials/Hydrology/Hackweek.ipynb:2155: ONy ==> only, on, one
Error: ./book/tutorials/Hydrology/Hackweek.ipynb:2203: Te ==> The, Be, We, To
Error: ./book/tutorials/Hydrology/Hackweek.ipynb:2203: bu ==> by, be, but, bug, bun, bud, buy, bum
Error: ./book/tutorials/Hydrology/Hackweek.ipynb:2271: Ths ==> The, This
Error: ./book/tutorials/Hydrology/Hackweek.ipynb:2271: bU ==> by, be, but, bug, bun, bud, buy, bum
```

Feel free to add words to ignore to this list:
https://github.com/ICESAT-2HackWeek/ICESat-2-Hackweek-2023/blob/tplshams-patch-1/.codespellignore

2023-08-08 16:29 UTC, jomey commented
@tplshams - I updated the notebook to be committed as the rendered version to overcome the challenge of not having access to the CryoHub from our GitHub actions. There were also some minor changes needed the directories to make it run.

2023-08-08 17:03 UTC, jomey commented on .github/workflows/qaqc.yaml
> +        skip: '*.js,qaqc.yml,acp_lidar_box.geojson,.codespellignore'
@scottyhq - I am suspicious that the QA/QC workflow didn't run after this change. Let's keep an eye on this

2023-08-08 23:02 UTC, merged