Submitting the Seabath project readme markdown
ICESAT-2HackWeek/ICESat-2-Hackweek-2023 pull request #99
Opened 2023-08-09 20:49 UTC by glacierSid

Merging the seabath project readme markdown with the ICESat-2-Hackweek-2023 main project

2023-08-09 21:56 UTC, jomey commented
Thank you for opening this PR @glacierSid 
Looks like a typo snuck into the ReadMe on Line 30
```
throught ==> thought ?
```

2023-08-09 21:56 UTC, jomey requested changes
Looks good after addressing the typo

2023-08-09 21:59 UTC, glacierSid commented
> Looks good after addressing the typo

Thanks Joe! :)

2023-08-10 17:58 UTC, jomey approved these changes

2024-07-18 17:04 UTC, merged